### PR TITLE
[LIB-598] update docs and docs links;

### PR DESCRIPTION
**Pull request by opalczynski**

### CODE REVIEW

**Comment by dancio** [comment]
lgtm, why tests are failing?

**Comment by opalczynski** [comment]
@dancio Extremely good question ;) But my tired brain yesterday can't process it :) Today with fresh and sharp mindset - Will try to answer to that question ;)

**Comment by opalczynski** [comment]
I made some test locally, and I'm almost sure that's is not the LIB issue and this is correlated with this:
https://github.com/Syncano/syncano-platform/pull/1003

The testing code:
```
connection = syncano.connect(
    host='https://api.syncano.rocks/',
    api_key='a47f5aceb80aedd8bbc626f8f27ebe5eea92d178',
    verify_ssl=False,
    instance_name='empty-tree-7742'
)

instance = Instance.please.get(name='empty-tree-7742')

user = instance.users.create(
    username='JozinZBazin{}'.format(randint(0, 200000)),
    password='jezioro',
)

SAMPLE_PROFILE_PIC = 'some_url_here41'

klass = user.profile.get_class_object()
klass.schema = [
    {'name': 'profile_pic', 'type': 'string'}
]

klass.save()
user.reload()  # force to refresh profile model;

user.profile.profile_pic = SAMPLE_PROFILE_PIC
user.profile.save()

**user = User.please.get(id=user.id)**

print(user.profile.profile_pic)
```

The marked line - api.rocks return sometimes data withour profile_pic:

```
{'links': {'self': '/v1.1/instances/empty-tree-7742/users/26/', 'groups': '/v1.1/instances/empty-tree-7742/users/26/groups/', 'profile': '/v1.1/instances/empty-tree-7742/classes/user_profile/objects/89/', 'reset-key': '/v1.1/instances/empty-tree-7742/users/26/reset_key/'}, 'groups': [], 'profile': {'other_permissions': 'none', 'updated_at': '2016-03-18T11:07:25.617560Z', 'links': {'self': '/v1.1/instances/empty-tree-7742/classes/user_profile/objects/89/', 'owner': '/v1.1/instances/empty-tree-7742/users/26/'}, 'group': None, 'owner_permissions': 'full', 'revision': 2, 'created_at': '2016-03-18T11:07:24.995110Z', 'channel_room': None, 'owner': 26, 'id': 89, 'group_permissions': 'none', 'channel': None}, 'id': 26, 'username': 'jozinzbazin69883', 'user_key': 'e255089a977fd43c50ddc8f9bdd41ba4839b6b34'}
```

And this one is correct:
```
{'profile': {'group_permissions': 'none', 'created_at': '2016-03-18T11:06:04.248859Z', 'id': 86, 'updated_at': '2016-03-18T11:06:04.559774Z', 'other_permissions': 'none', 'group': None, 'revision': 2, 'profile_pic': 'some_url_here41', 'owner_permissions': 'full', 'links': {'owner': '/v1.1/instances/empty-tree-7742/users/23/', 'self': '/v1.1/instances/empty-tree-7742/classes/user_profile/objects/86/'}, 'channel': None, 'owner': 23, 'channel_room': None}, 'username': 'jozinzbazin6972', 'groups': [], 'id': 23, 'links': {'profile': '/v1.1/instances/empty-tree-7742/classes/user_profile/objects/86/', 'reset-key': '/v1.1/instances/empty-tree-7742/users/23/reset_key/', 'groups': '/v1.1/instances/empty-tree-7742/users/23/groups/', 'self': '/v1.1/instances/empty-tree-7742/users/23/'}, 'user_key': 'df9cf17d5f8c4dd9381a0c6faf2117f8b630c40c'}
```

**Comment by opalczynski** [comment]
@dancio Told ya it was a core issue :) 

I want to push here also some correct after work with parse module ;) One line and link updates in docs. So do not merge pls :)

**Comment by 23doors** [comment]
@opalczynski to be fair it was a core issue that your changes introduced :P specifically https://github.com/Syncano/syncano-platform/pull/992

**Comment by opalczynski** [comment]
@23doors yep :) know that. But you fixed it so fast that haven't time for reaction ;) anyway. Good that it is good now. Thanks.

**Pull request merged**
