### PR TITLE
Fixed readme formatting issues

### PR DESCRIPTION
**Pull request by lifcio**
Extra line is needed between :: and code examples

@EricSchles I didn't commit it directly to master, since I didn't know if you're still working on the readme in your fork.
Also, if needed feel free to change from rst to mk if you think that's a better fit.

### CODE REVIEW

**Comment by atteroTheGreatest** [comment]
I see that we have some kind of improve readme contest here ;). I also published a PR because I was so annoyed with lack of code highlighting and wrong python indentation, wrrr. ;).

**Comment by lifcio** [comment]
Hey, iOS guy cared about Python code enough to fix readme at midnight, don't laugh at me ;)

**Comment by atteroTheGreatest** [comment]
@lifcio I'm laughing with you, not at you ;). We're all in the same team and I'm very happy that we're so active here. Yay!

**Comment by atteroTheGreatest** [comment]
Fixing readme!

**Pull request merged**
