### PR TITLE
Ran 2to3 in order to implement Python3 compatibility.

### PR DESCRIPTION
**Pull request by markrjr**
I ran [2to3](https://docs.python.org/2/library/2to3.html) in order to introduce rudimentary Python 3 compatibility. Ideally, you would merge this into it a separate Python 3 branch. I was able to do some preliminary testing and the library seems to still work fine, however, I wasn't able to run your proprietary tests to ensure full compatibility.

2to3 creates backup files for each file it edits, hence the ".bak" extension.

### CODE REVIEW

**Comment by markrjr** [comment]
I'm not quite sure what the issue is on this commit.

ERROR: /home/ubuntu/syncano-python/tests/integration_test_accounts.py Imports are incorrectly sorted. ./run_tests.sh returned exit code 1

Was the build error, in the last commit I did add an import, but I'm unsure of where to move it to fix the problem.

**Comment by Zhebr** [comment]
@markrjr Thank you for the PR. Please use isort for managing import order.

**Comment by opalczynski** [comment]
Hi, @markrjr I've checked this PR - and must say that overall idea is good - to support python3, but sadly - 2to3 is not enough. I will try to came out with this topic on ours closest library meeting. For now - I think we should close this pr.

**Comment by markrjr** [comment]
It would seem that that is in fact the case. You guys have a really great service stack, but the Python 3 incompatibility is sort of a deal breaker.

**Comment by opalczynski** [comment]
Hi @markrjr,

Today we release version 5.0.0 of our lib which supports python3 :) Happy coding!

Note that this version is using new naming and API - so it's not backward compatible - in some cases;

Also - we are preparing a big release today - so it will be fully operable tomorrow.

Have a nice day.

**Comment by markrjr** [comment]
This is awesome!

Thank you so much!

**Pull request closed without merging**
