### PR TITLE
[SYNPYTH-39] SchemaFiled & SchemaManager

### PR DESCRIPTION
**Pull request by dancio**
Few examples:

```python
cls.schema                              # SchemaManager instance
cls.schema[0]                           # access via index
cls.schema['henryk']                    # access via schema field name
cls.schema.add({}, {}, {})              # add many objects at once
cls.schema.remove('henryk', 'ala')      # remove many objects at once
cls.schema.clear()                      # clear all entries

# Index managment
cls.schema.set_index('henryk', order=True)
cls.schema.set_index('henryk', filter=True)
cls.schema.set_index('henryk', order=True, filter=True)
cls.schema.set_order_index('henryk')
cls.schema.set_filter_index('henryk')
cls.schema.remove_index('henryk', order=True, filter=True)
cls.schema.remove_order_index(...)
cls.schema.remove_filter_index(...)
```

### CODE REVIEW

**Comment by dancio** [comment]
@atteroTheGreatest maybe we should use `OrderedDict` as storage and add some more validation on `SchemaManager` level?

**Comment by 23doors** [comment]
Looks pretty neat to me. Although instead of:
```python
cls.schema.set_index('henryk', 'order_index')
```
I would prefer:
```python
cls.schema.set_index('henryk', order_index=True)
cls.schema.set_index('henryk', order_index=True, filter_index=True)
```
And raise error when both arguments are False.
As right now it is possible to set invalid (non existing) index and without more in depth knowledge it's impossible to deduce what are possible indexes. This way you can simply check the signature of that method in library. About OrderedDict - a list of dict is pretty much the same and more in line with what we actually store so no big difference in my opinion.

**Comment by dancio** [comment]
@23doors good idea but maybe we should remove `_index` suffix from arguments? e.g `set_index('henryk', order=True, filter=True)`

**Comment by 23doors** [comment]
Right! Even better this way.

**Pull request merged**
