### PR TITLE
[LIB-311] rework count DataObject manager method;

### PR DESCRIPTION
**Pull request by opalczynski**
count() now returns objects, count tuple;

### CODE REVIEW

**Comment by Zhebr** [comment]
shouldn't there be some deprecation warning? do we really want this to be the same named ```count``` method as previously?

**Comment by opalczynski** [comment]
It's a hard question :) 

How would you name this method? 'objects_count'? Thinking of it when implementing and can't fugre it out something appropriate. 

And yes, I break backward compatibility here. But count() is quite new and assumed that its no harm here (probably wrong).

**Comment by Zhebr** [comment]
hmm... wonder if it shouldn't be some flag in listing objects to add this count; I mean - not count giving objects, but objects giving count; what do you think?

**Comment by opalczynski** [comment]
@Zhebr Do you like it now?

**Comment by opalczynski** [comment]
:+1: for picture!

**Pull request merged**
