### PR TITLE
[LIB-261] Allow to refresh connection;

### PR DESCRIPTION
**Pull request by opalczynski**
…re defaul_connection in registry; allow now to refresh the connection;

### CODE REVIEW

**Comment by dancio** [comment]
lgtm

**Comment by lifcio** [comment]
I know it's an old PR - but how to use it now, after changes?

**Comment by opalczynski** [comment]
@lifcio 

I move the default connection initialization from file and create it when syncano.connect() is called.

So every time you do: syncano.connect() there should be new connection object made.

**Comment by lifcio** [comment]
Sounds great, thanks!

**Pull request merged**
